source :rubygems
gem "rspec", "1.3.0"
gem "activesupport", "3.0.4"
gem "activerecord", "3.0.4"
gem "activemodel", "3.0.4"
gem "sqlite3-ruby", "1.2.5"
gem "mongo_mapper", "0.8.2"
gem "mongoid", "2.0.0"
gem "mocha", "0.9.8"
gem "ruby-debug"
gem "yard"
